### ISSUE TITLE
AOT Compatbility / Source Generation

### ISSUE THREAD

**Issue by RichiCoder1** [Natsumi-sama/OscQueryLibrary#8]
Howdy! I used this library to get a basic Osc/VRChat app up and running and it's been great! It's a little console app, so I was planning to package it up with the new C# AOT features however I ran into an issue that it'd require this library to add JSON Source Generation.

It's pretty easy to add and I'm happy to submit a PR if you'd like!

**Comment by LucHeart** [comment]
Feel free to make a PR. This shouldnt hurt performance and shouldnt break anything afaik.
